import os

from dotenv import load_dotenv

load_dotenv()

WILDLENS_FOOTPRINT_MULTICLASS_CLASSIFIER_MODEL_PATH = os.getenv("WILDLEN_FOOTPRINT_CLASSIFIER_MODEL_PATH")
WILDLENS_FOOTPRINT_BINARY_CLASSIFIER_MODEL_PATH = os.getenv("WILDLEN_FOOTPRINT_BINARY_CLASSIFIER_MODEL_PATH")
WILDLENS_FOOTPRINT_BINARY_CLASSIFICATION_THRESHOLD = float(os.getenv("WILDLEN_FOOTPRINT_BINARY_CLASSIFICATION_THRESHOLD"))
