import os

from dotenv import load_dotenv

load_dotenv()

WILDLEN_FOOTPRINT_MULTICLASS_CLASSIFIER_MODEL_PATH = os.getenv("WILDLEN_FOOTPRINT_CLASSIFIER_MODEL_PATH")
WILDLEN_FOOTPRINT_BINARY_CLASSIFIER_MODEL_PATH = os.getenv("WILDLEN_FOOTPRINT_BINARY_CLASSIFIER_MODEL_PATH")
